theme: jekyll-theme-cayman

navigation:
- title: Introduction
  url: https://sarathtd406.github.io/Git-tutorial-101/#

- title: Install Git
  url: https://sarathtd406.github.io/Git-tutorial-101/#1-install-git
  
- title: Configure Git
  url: https://sarathtd406.github.io/Git-tutorial-101/#2-configure-git

- title: Create and Initialize a Project
  url: https://sarathtd406.github.io/Git-tutorial-101/#3-create-and-initialize-a-project

- title: Check the status of our project
  url: https://sarathtd406.github.io/Git-tutorial-101/#4-check-the-status-of-our-project

- title: Basic Concept
  url: https://sarathtd406.github.io/Git-tutorial-101/#basic-concept

- title: Create new files (simple txt file)
  url: https://sarathtd406.github.io/Git-tutorial-101/#5-create-new-files-simple-txt-file

- title: Add files to the Staging Area
  url: https://sarathtd406.github.io/Git-tutorial-101/#6-add-files-to-the-staging-area
